// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __TauStar_h__
#define __TauStar_h__

#include "TauStar_RcppExports.h"

#endif // __TauStar_h__
