// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// TStarFastTiesRCPP
Rcpp::NumericVector TStarFastTiesRCPP(NumericVector xNumeric, NumericVector yNumeric);
RcppExport SEXP TauStar_TStarFastTiesRCPP(SEXP xNumericSEXP, SEXP yNumericSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type xNumeric(xNumericSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type yNumeric(yNumericSEXP );
        Rcpp::NumericVector __result = TStarFastTiesRCPP(xNumeric, yNumeric);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// VTStarFastTiesRCPP
Rcpp::NumericVector VTStarFastTiesRCPP(NumericVector xNumeric, NumericVector yNumeric);
RcppExport SEXP TauStar_VTStarFastTiesRCPP(SEXP xNumericSEXP, SEXP yNumericSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type xNumeric(xNumericSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type yNumeric(yNumericSEXP );
        Rcpp::NumericVector __result = VTStarFastTiesRCPP(xNumeric, yNumeric);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
