// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/TauStar.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// HoeffIndCdfRCPP
arma::vec HoeffIndCdfRCPP(arma::vec x, double maxError);
static SEXP TauStar_HoeffIndCdfRCPP_try(SEXP xSEXP, SEXP maxErrorSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type maxError(maxErrorSEXP);
    __result = Rcpp::wrap(HoeffIndCdfRCPP(x, maxError));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_HoeffIndCdfRCPP(SEXP xSEXP, SEXP maxErrorSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_HoeffIndCdfRCPP_try(xSEXP, maxErrorSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// HoeffIndPdfRCPP
arma::vec HoeffIndPdfRCPP(arma::vec x, double maxError);
static SEXP TauStar_HoeffIndPdfRCPP_try(SEXP xSEXP, SEXP maxErrorSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type maxError(maxErrorSEXP);
    __result = Rcpp::wrap(HoeffIndPdfRCPP(x, maxError));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_HoeffIndPdfRCPP(SEXP xSEXP, SEXP maxErrorSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_HoeffIndPdfRCPP_try(xSEXP, maxErrorSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// eigenForDiscreteProbs
arma::vec eigenForDiscreteProbs(arma::vec p);
static SEXP TauStar_eigenForDiscreteProbs_try(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::vec >::type p(pSEXP);
    __result = Rcpp::wrap(eigenForDiscreteProbs(p));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_eigenForDiscreteProbs(SEXP pSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_eigenForDiscreteProbs_try(pSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// HoeffIndDiscreteCdfRCPP
arma::vec HoeffIndDiscreteCdfRCPP(arma::vec x, arma::vec eigenP, arma::vec eigenQ, double maxError);
static SEXP TauStar_HoeffIndDiscreteCdfRCPP_try(SEXP xSEXP, SEXP eigenPSEXP, SEXP eigenQSEXP, SEXP maxErrorSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eigenP(eigenPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eigenQ(eigenQSEXP);
    Rcpp::traits::input_parameter< double >::type maxError(maxErrorSEXP);
    __result = Rcpp::wrap(HoeffIndDiscreteCdfRCPP(x, eigenP, eigenQ, maxError));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_HoeffIndDiscreteCdfRCPP(SEXP xSEXP, SEXP eigenPSEXP, SEXP eigenQSEXP, SEXP maxErrorSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_HoeffIndDiscreteCdfRCPP_try(xSEXP, eigenPSEXP, eigenQSEXP, maxErrorSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// HoeffIndDiscretePdfRCPP
arma::vec HoeffIndDiscretePdfRCPP(arma::vec x, arma::vec eigenP, arma::vec eigenQ, double maxError);
static SEXP TauStar_HoeffIndDiscretePdfRCPP_try(SEXP xSEXP, SEXP eigenPSEXP, SEXP eigenQSEXP, SEXP maxErrorSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eigenP(eigenPSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eigenQ(eigenQSEXP);
    Rcpp::traits::input_parameter< double >::type maxError(maxErrorSEXP);
    __result = Rcpp::wrap(HoeffIndDiscretePdfRCPP(x, eigenP, eigenQ, maxError));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_HoeffIndDiscretePdfRCPP(SEXP xSEXP, SEXP eigenPSEXP, SEXP eigenQSEXP, SEXP maxErrorSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_HoeffIndDiscretePdfRCPP_try(xSEXP, eigenPSEXP, eigenQSEXP, maxErrorSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// HoeffIndMixedCdfRCPP
arma::vec HoeffIndMixedCdfRCPP(arma::vec x, arma::vec eigenP, double maxError);
static SEXP TauStar_HoeffIndMixedCdfRCPP_try(SEXP xSEXP, SEXP eigenPSEXP, SEXP maxErrorSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eigenP(eigenPSEXP);
    Rcpp::traits::input_parameter< double >::type maxError(maxErrorSEXP);
    __result = Rcpp::wrap(HoeffIndMixedCdfRCPP(x, eigenP, maxError));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_HoeffIndMixedCdfRCPP(SEXP xSEXP, SEXP eigenPSEXP, SEXP maxErrorSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_HoeffIndMixedCdfRCPP_try(xSEXP, eigenPSEXP, maxErrorSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// HoeffIndMixedPdfRCPP
arma::vec HoeffIndMixedPdfRCPP(arma::vec x, arma::vec eigenP, double maxError);
static SEXP TauStar_HoeffIndMixedPdfRCPP_try(SEXP xSEXP, SEXP eigenPSEXP, SEXP maxErrorSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eigenP(eigenPSEXP);
    Rcpp::traits::input_parameter< double >::type maxError(maxErrorSEXP);
    __result = Rcpp::wrap(HoeffIndMixedPdfRCPP(x, eigenP, maxError));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_HoeffIndMixedPdfRCPP(SEXP xSEXP, SEXP eigenPSEXP, SEXP maxErrorSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_HoeffIndMixedPdfRCPP_try(xSEXP, eigenPSEXP, maxErrorSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// TStarHellerAndHellerRCPP
double TStarHellerAndHellerRCPP(const arma::vec& x, const arma::vec& y);
static SEXP TauStar_TStarHellerAndHellerRCPP_try(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    __result = Rcpp::wrap(TStarHellerAndHellerRCPP(x, y));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_TStarHellerAndHellerRCPP(SEXP xSEXP, SEXP ySEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_TStarHellerAndHellerRCPP_try(xSEXP, ySEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// VTStarHellerAndHellerRCPP
double VTStarHellerAndHellerRCPP(const arma::vec& x, const arma::vec& y);
static SEXP TauStar_VTStarHellerAndHellerRCPP_try(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    __result = Rcpp::wrap(VTStarHellerAndHellerRCPP(x, y));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_VTStarHellerAndHellerRCPP(SEXP xSEXP, SEXP ySEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_VTStarHellerAndHellerRCPP_try(xSEXP, ySEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// TStarWeihsEtAlRCPP
Rcpp::NumericVector TStarWeihsEtAlRCPP(NumericVector xNumeric, NumericVector yNumeric);
static SEXP TauStar_TStarWeihsEtAlRCPP_try(SEXP xNumericSEXP, SEXP yNumericSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericVector >::type xNumeric(xNumericSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yNumeric(yNumericSEXP);
    __result = Rcpp::wrap(TStarWeihsEtAlRCPP(xNumeric, yNumeric));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_TStarWeihsEtAlRCPP(SEXP xNumericSEXP, SEXP yNumericSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_TStarWeihsEtAlRCPP_try(xNumericSEXP, yNumericSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// VTStarWeihsEtAlRCPP
Rcpp::NumericVector VTStarWeihsEtAlRCPP(NumericVector xNumeric, NumericVector yNumeric);
static SEXP TauStar_VTStarWeihsEtAlRCPP_try(SEXP xNumericSEXP, SEXP yNumericSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericVector >::type xNumeric(xNumericSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yNumeric(yNumericSEXP);
    __result = Rcpp::wrap(VTStarWeihsEtAlRCPP(xNumeric, yNumeric));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_VTStarWeihsEtAlRCPP(SEXP xNumericSEXP, SEXP yNumericSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_VTStarWeihsEtAlRCPP_try(xNumericSEXP, yNumericSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// TStarFastResampleRCPP
Rcpp::NumericVector TStarFastResampleRCPP(NumericVector xNumeric, NumericVector yNumeric, int numResamples, int sampleSize);
static SEXP TauStar_TStarFastResampleRCPP_try(SEXP xNumericSEXP, SEXP yNumericSEXP, SEXP numResamplesSEXP, SEXP sampleSizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericVector >::type xNumeric(xNumericSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type yNumeric(yNumericSEXP);
    Rcpp::traits::input_parameter< int >::type numResamples(numResamplesSEXP);
    Rcpp::traits::input_parameter< int >::type sampleSize(sampleSizeSEXP);
    __result = Rcpp::wrap(TStarFastResampleRCPP(xNumeric, yNumeric, numResamples, sampleSize));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_TStarFastResampleRCPP(SEXP xNumericSEXP, SEXP yNumericSEXP, SEXP numResamplesSEXP, SEXP sampleSizeSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_TStarFastResampleRCPP_try(xNumericSEXP, yNumericSEXP, numResamplesSEXP, sampleSizeSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}
// TStarNaiveRCPP
Rcpp::NumericVector TStarNaiveRCPP(NumericVector x, NumericVector y, bool vStat);
static SEXP TauStar_TStarNaiveRCPP_try(SEXP xSEXP, SEXP ySEXP, SEXP vStatSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type vStat(vStatSEXP);
    __result = Rcpp::wrap(TStarNaiveRCPP(x, y, vStat));
    return __result;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP TauStar_TStarNaiveRCPP(SEXP xSEXP, SEXP ySEXP, SEXP vStatSEXP) {
    SEXP __result;
    {
        Rcpp::RNGScope __rngScope;
        __result = PROTECT(TauStar_TStarNaiveRCPP_try(xSEXP, ySEXP, vStatSEXP));
    }
    Rboolean __isInterrupt = Rf_inherits(__result, "interrupted-error");
    if (__isInterrupt) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean __isError = Rf_inherits(__result, "try-error");
    if (__isError) {
        SEXP __msgSEXP = Rf_asChar(__result);
        UNPROTECT(1);
        Rf_error(CHAR(__msgSEXP));
    }
    UNPROTECT(1);
    return __result;
}

// validate (ensure exported C++ functions exist before calling them)
static int TauStar_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("arma::vec(*HoeffIndCdfRCPP)(arma::vec,double)");
        signatures.insert("arma::vec(*HoeffIndPdfRCPP)(arma::vec,double)");
        signatures.insert("arma::vec(*eigenForDiscreteProbs)(arma::vec)");
        signatures.insert("arma::vec(*HoeffIndDiscreteCdfRCPP)(arma::vec,arma::vec,arma::vec,double)");
        signatures.insert("arma::vec(*HoeffIndDiscretePdfRCPP)(arma::vec,arma::vec,arma::vec,double)");
        signatures.insert("arma::vec(*HoeffIndMixedCdfRCPP)(arma::vec,arma::vec,double)");
        signatures.insert("arma::vec(*HoeffIndMixedPdfRCPP)(arma::vec,arma::vec,double)");
        signatures.insert("double(*TStarHellerAndHellerRCPP)(const arma::vec&,const arma::vec&)");
        signatures.insert("double(*VTStarHellerAndHellerRCPP)(const arma::vec&,const arma::vec&)");
        signatures.insert("Rcpp::NumericVector(*TStarWeihsEtAlRCPP)(NumericVector,NumericVector)");
        signatures.insert("Rcpp::NumericVector(*VTStarWeihsEtAlRCPP)(NumericVector,NumericVector)");
        signatures.insert("Rcpp::NumericVector(*TStarFastResampleRCPP)(NumericVector,NumericVector,int,int)");
        signatures.insert("Rcpp::NumericVector(*TStarNaiveRCPP)(NumericVector,NumericVector,bool)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP TauStar_RcppExport_registerCCallable() { 
    R_RegisterCCallable("TauStar", "TauStar_HoeffIndCdfRCPP", (DL_FUNC)TauStar_HoeffIndCdfRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_HoeffIndPdfRCPP", (DL_FUNC)TauStar_HoeffIndPdfRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_eigenForDiscreteProbs", (DL_FUNC)TauStar_eigenForDiscreteProbs_try);
    R_RegisterCCallable("TauStar", "TauStar_HoeffIndDiscreteCdfRCPP", (DL_FUNC)TauStar_HoeffIndDiscreteCdfRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_HoeffIndDiscretePdfRCPP", (DL_FUNC)TauStar_HoeffIndDiscretePdfRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_HoeffIndMixedCdfRCPP", (DL_FUNC)TauStar_HoeffIndMixedCdfRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_HoeffIndMixedPdfRCPP", (DL_FUNC)TauStar_HoeffIndMixedPdfRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_TStarHellerAndHellerRCPP", (DL_FUNC)TauStar_TStarHellerAndHellerRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_VTStarHellerAndHellerRCPP", (DL_FUNC)TauStar_VTStarHellerAndHellerRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_TStarWeihsEtAlRCPP", (DL_FUNC)TauStar_TStarWeihsEtAlRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_VTStarWeihsEtAlRCPP", (DL_FUNC)TauStar_VTStarWeihsEtAlRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_TStarFastResampleRCPP", (DL_FUNC)TauStar_TStarFastResampleRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_TStarNaiveRCPP", (DL_FUNC)TauStar_TStarNaiveRCPP_try);
    R_RegisterCCallable("TauStar", "TauStar_RcppExport_validate", (DL_FUNC)TauStar_RcppExport_validate);
    return R_NilValue;
}
